// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4IoPqj5LM9blmMEBamUwSYUtOlnv4EvQ',
    appId: '1:74398229766:web:d4384ee8a3cedb8a286a87',
    messagingSenderId: '74398229766',
    projectId: 'gym-royale-a4ca4',
    authDomain: 'gym-royale-a4ca4.firebaseapp.com',
    storageBucket: 'gym-royale-a4ca4.firebasestorage.app',
    measurementId: 'G-HRR95RBQVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJmR2FRprxPc2RLNncPGQDGRkA7q1c92E',
    appId: '1:74398229766:android:92efdfb03098893b286a87',
    messagingSenderId: '74398229766',
    projectId: 'gym-royale-a4ca4',
    storageBucket: 'gym-royale-a4ca4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpeP5rrdGriOqUD8Y-dv7mdYSa2JwEkZc',
    appId: '1:74398229766:ios:2400e609e6428e7a286a87',
    messagingSenderId: '74398229766',
    projectId: 'gym-royale-a4ca4',
    storageBucket: 'gym-royale-a4ca4.firebasestorage.app',
    iosBundleId: 'com.example.gymroyale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpeP5rrdGriOqUD8Y-dv7mdYSa2JwEkZc',
    appId: '1:74398229766:ios:2400e609e6428e7a286a87',
    messagingSenderId: '74398229766',
    projectId: 'gym-royale-a4ca4',
    storageBucket: 'gym-royale-a4ca4.firebasestorage.app',
    iosBundleId: 'com.example.gymroyale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4IoPqj5LM9blmMEBamUwSYUtOlnv4EvQ',
    appId: '1:74398229766:web:5ad6ea8f294f6d75286a87',
    messagingSenderId: '74398229766',
    projectId: 'gym-royale-a4ca4',
    authDomain: 'gym-royale-a4ca4.firebaseapp.com',
    storageBucket: 'gym-royale-a4ca4.firebasestorage.app',
    measurementId: 'G-625CTF7QHW',
  );

}